/**
 * back-rate-limit
 * My application with Recaptcha v3 and Bucket4j
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface JwtTokenDTO { 
    token?: string;
}